### PR TITLE
Properties must be hyphenated in html

### PR DESCRIPTION
**Pull request by BennyAlex**

### CODE REVIEW

**Comment by BennyAlex** [comment]
@alessiomaffeis are you alive?

**Comment by lindbergtobias** [comment]
+1

**Comment by BennyAlex** [comment]
@tobyryuk why thumbs down?

**Comment by tobyryuk** [comment]
Because it was a super unnecessary comment since this PR is only for changing the README.

**Comment by BennyAlex** [comment]
@tobyryuk I also published another pull request and @alessiomaffeis  didn't respond

**Comment by tobyryuk** [comment]
He has no obligation to respond to you though 😕

**Comment by BennyAlex** [comment]
No words...

**Comment by alessiomaffeis** [comment]
Yes, I am alive. But I also have a life.
All of this was pretty sad and unnecessary, both the thread and the PR, but I merged it anyway.

Have a nice weekend!

**Comment by tobyryuk** [comment]
If there's anything you don't like in this component, maybe you should file a PR?

**Comment by BennyAlex** [comment]
I already did so stfu

**Pull request merged**
